#!/bin/sh

set -e

export MAKE="make --jobs $(nproc)"

bundle install --jobs $(nproc)
bundle exec rake db:create db:migrate
OPENPROJECT_DISABLE_RELOADING=true bundle exec rake db:seed
bundle exec rake openproject:plugins:register_frontend
bundle exec rake assets:export_locales
